package nl.NG.Jetfightergame.GameState;

import nl.NG.Jetfightergame.AbstractEntities.MovingEntity;
import nl.NG.Jetfightergame.Engine.GameTimer;
import nl.NG.Jetfightergame.Tools.Vectors.Color4f;
import nl.NG.Jetfightergame.Tools.Vectors.DirVector;
import nl.NG.Jetfightergame.Tools.Vectors.PosVector;

import java.util.Collection;

/**
 * entities generated by other entities can leave them with objects implementing this interface.
 * These classes should make sure that all required actions are taken to implement the new entity into the game
 * @author Geert van Ieperen
 * created on 5-2-2018.
 */
public interface SpawnReceiver {

    /**
     * adds an moving entity to the game's collision detection and rendering
     * @param spawn the new entity
     */
    void addSpawn(MovingEntity.Spawn spawn);

    /**
     * add multiple new entities
     * @see #addSpawn(MovingEntity.Spawn)
     */
    default void addSpawns(Collection<MovingEntity.Spawn> spawn){
        for (MovingEntity.Spawn entity : spawn) {
            addSpawn(entity);
        }
    }

    /**
     * adds an explosion to the world
     * @param position
     * @param direction
     * @param spread
     * @param color1
     * @param color2
     */
    void addExplosion(PosVector position, DirVector direction, float spread, Color4f color1, Color4f color2);

    GameTimer getTimer();
}
