package nl.NG.Jetfightergame.Rendering.MatrixStack;

/**
 * @author Geert van Ieperen
 *         created on 17-11-2017.
 */
public interface Renderable {
    /**
     * draws the object on the gl buffer. This method may only be called by a class that implements GL2
     * @param lock a non-null object that can only be generated by a GL2 object.
     */
    void render(GL2.Painter lock);

    void dispose();
}
